### ISSUE TITLE
Failed to load json data

### ISSUE THREAD

**Issue by gsimond** [moisseev/BackupPC_Timeline#1]
Failed to load json data from /BackupPC_TimeLine?action=timelineJSON&days=3&1598285357679
Internal Server Error

**Comment by moisseev** [comment]
@gsimond Would you check if the c34ea63c2283af27da3a9d5961c91a9e5b32c364 fixes the issue?
"Internal Server Error" is not an informative error message, so I am not quite sure if the fixed bug is related to your problem.

**Comment by gsimond** [comment]
Hi Alexander

thanks a lot 
this fixes the issue

best regards

Gilles Simond
